# Generated by Django 3.2.6 on 2022-02-08 04:04

import bstgames.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=50, unique=True, verbose_name='Game')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('age_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(18)], verbose_name='Age Rating')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=50, unique=True, verbose_name='Developer')),
            ],
            options={
                'verbose_name': 'Game Developer',
                'verbose_name_plural': 'Game Developers',
            },
        ),
        migrations.CreateModel(
            name='GameGameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bstgames_game_genre',
            },
        ),
        migrations.CreateModel(
            name='GameGamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metascore', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Metascore')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
            ],
            options={
                'db_table': 'bstgames_game_platform',
            },
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, unique=True, verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Game Genre',
                'verbose_name_plural': 'Game Genres',
            },
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, unique=True, verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Game Platform',
                'verbose_name_plural': 'Game Platforms',
            },
        ),
        migrations.CreateModel(
            name='GamePublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50, unique=True, verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Game Publisher',
                'verbose_name_plural': 'Game Publishers',
            },
        ),
        migrations.CreateModel(
            name='GamePlatformImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(upload_to=bstgames.models.image_upload_path, verbose_name='Image')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('gamegameplatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bstgames.gamegameplatform')),
            ],
        ),
        migrations.CreateModel(
            name='GameMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Trade')], verbose_name='Action')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], verbose_name='Status')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('gameplatform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bstgames.gamegameplatform', verbose_name='Game - Platform')),
                ('trade', models.ManyToManyField(blank=True, related_name='trades', to='bstgames.GameGamePlatform', verbose_name='Trade For')),
            ],
            options={
                'verbose_name': 'Game Market',
                'verbose_name_plural': 'Game Markets',
            },
        ),
    ]
